version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  service1:
    build:
      context: ./service1
    container_name: service1
    networks:
      - app-network
    expose:
      - "5001"

  service2:
    build:
      context: ./service2
    container_name: service2
    networks:
      - app-network
    expose:
      - "5002"

networks:
  app-network:
    driver: bridge  # Внутренняя сеть
