version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    networks:
      - app-network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  app-network:
    external: true
