version: '3.8'

services:
  logstash:
    build: .
    container_name: logstash
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Внутренняя сеть